use db_pet;

CREATE TABLE IF NOT EXISTS DONO(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR (255),
DATANASCIMENTO DATE,
PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS TB_GATOS(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR (255),
DONO VARCHAR (255),
DATANASCIMENTO DATE,
PRIMARY KEY(ID)

);

INSERT INTO tb_gatos (NOME, ID_DONO) values ("yuki", 1);
INSERT INTO tb_gatos (NOME, ID_DONO) values ("haru", 2);
INSERT INTO DONO (NOME) values ("BRUNA");
INSERT INTO DONO (NOME) values ("RAFAEL");
