CREATE DEFINER = CURRENT_USER 
TRIGGER `CARLOCA`.`LOCACOES_BEFORE_INSERT` BEFORE INSERT ON `LOCACOES` FOR EACH ROW
BEGIN
   IF EXISTS (SELECT situacao FROM CARROS WHERE ID = NEW.ID_CARROS AND situacao != 'disponivel') THEN
        SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'Carro não disponível para aluguel';
    END IF;
END;